export const tbCoupons: ICoupon[] = [
  {
    name: "满300减50",
    type: "target",
    order: 0,
    times: 99999,
    repeat: true,
    target: 300,
    reduce: 50,
  },
  {
    name: "购物券1200-110",
    type: "target",
    order: 1,
    times: 1,
    repeat: false,
    target: 1200,
    reduce: 110,
  },
  {
    name: "88vip打折",
    type: "sale",
    order: 3,
    times: 9999,
    repeat: false,
    target: 0,
    sale: 0.95,
  },
  {
    name: "88vip优惠套餐",
    type: "group",
    order: 4,
    times: 99,
    repeat: false,
    group: [
      {
        name: "6800-500",
        type: "target",
        times: 1,
        order: 0,
        repeat: false,
        target: 6800,
        reduce: 500,
      },
      {
        name: "3800-300",
        type: "target",
        times: 1,
        order: 0,
        repeat: false,
        target: 3800,
        reduce: 300,
      },
      {
        name: "1000-50",
        type: "target",
        times: 1,
        order: 0,
        repeat: false,
        target: 1000,
        reduce: 50,
      },
    ],
  },
];
